name: Checkmarx One Scan (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cxone_scan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CxOne CLI
        run: |
          Invoke-WebRequest -Uri "https://download.checkmarx.com/CxOne/CLI/latest/ast-cli_windows_x64.zip" -OutFile "cx.zip"
          Expand-Archive -Path "cx.zip" -DestinationPath "cx"
          # Optional: verify executable exists
          dir .\cx\

      - name: Run Checkmarx One Scan
        env:
          CX_CLIENT_ID: "Github_Action"
          CX_CLIENT_SECRET: "OMQAEmBGeogdgYllXKtAbD6XgBfYNa12"
          CX_BASE_URI: "https://ind.ast.checkmarx.net"
          CX_TENANT: "cx_ind_internal_test"
        run: |
          $cx = ".\cx\cx.exe"
          & $cx scan create `
            --project-name "${{ secrets.CX_PROJECT }}" `
            --branch "master" `
            --report-format summary `
            --output-path results\ `
            --scan-types sast,sca `
            --threshold sast-high=1
            "$PWD"

      - name: Upload Scan Report1
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cxone-scan-results
          path: results\
